
name: Build Windows

on:
  workflow_dispatch:
  pull_request:
    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        
      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable-gnu
          default: yes

      - name: Show version
        shell: msys2 {0}
        run: cargo --version
          | rustup toolchain list
